name: my workflow                     
on: [push]                            

jobs:                                 
  build:                              
    name: hello github action         
    runs-on: ubuntu-18.04             
    steps:                            
      - name: checkout source code    
        uses: actions/checkout@dev-action-test
      - name: echo Hello              
        run: echo "Hello" 
